### ISSUE TITLE
Need Refactoring

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/discord-bot#2]
**Is your feature request related to a problem? Please describe.**
All the code is dumped in one single file, which is creating a mess in understanding and working with the code. 

**Describe the solution you'd like**
I believe creating modules for different commands would be better. 

Additional: Last commit to update readme added a duplicate [discord-bot.svg](https://github.com/gdsclpu/discord-bot/blob/main/discord-bot.svg) in the root folder, which is not being used and a copy is already present is asset folder. Delete this svg.

**Comment by shubhansu-kr** [comment]
I would like to start creating modules step by step. 

For starter I am thinking of creating a src folder and create modules for all the quotes and image source links  inside it. 

Do let me know if you have any specific directory structure to follow. 

Thanks.

**Comment by NikhilMahana** [comment]
Hey @shubhansu-kr,
An issue was created to re-frame the complete code and break them down into modules.
However, please make sure to study the functionality prior.
Additionally, you may remove the extra assests, and also feel free to ping us on discord for any assistance.

**Comment by shubhansu-kr** [comment]
Hey @NikhilMahana,
Thanks for assigning me this issue, i will surely  be reading the functionality and documentation. 
I will keep you posted with the updates and advances. 

Thanks You

**Comment by RakeshPotnuru** [comment]
@shubhansu-kr 
Any update on this issue?

**Comment by shubhansu-kr** [comment]
> @shubhansu-kr 
> Any update on this issue?

Hey @RakeshPotnuru, 
I created a pull #3 for the same. 

I am thinking of breaking the app in further modules. 
Do let me know if you have any ideas of yours for breakdown.

**Comment by RakeshPotnuru** [comment]
@shubhansu-kr 
Yes, go ahead.
But first, create an issue so that we can track what's going on.

**Comment by RakeshPotnuru** [comment]
Whenever you make a PR, please mention the issue number in that PR.
